// 这是你放旅行照片的地方，每个省份分“风景”和“美食”两个栏目。
// 例如：把照片保存到 travel/北京/风景/1.jpg 和 travel/北京/美食/1.jpg，然后写：
// "北京": {
//   "风景": ["travel/北京/风景/1.jpg"],
//   "美食": ["travel/北京/美食/1.jpg"]
// }

window.TRAVEL_PHOTOS = {
  "北京": [],
  "天津": [],
  "河北": [],
  "山西": [],
  "内蒙古": [],
  "辽宁": [],
  "吉林": [],
  "黑龙江": [],
  "上海": [],
  "江苏": [],
  "浙江": [],
  "安徽": [],
  "福建": [],
  "江西": [],
  "山东": [],
  "河南": [],
  "湖北": [],
  "湖南": [],
  "广东": [],
  "广西": [],
  "海南": {
    "风景": [
      "travel/海南/风景/yemeng-changlang.jpg",
      "travel/海南/风景/lingshui-night.jpg",
      "travel/海南/风景/sanya-bay.jpg",
      "travel/海南/风景/daboluo-mall.jpg",
      "travel/海南/风景/park-path.jpg",
      "travel/海南/风景/lingshui-beach.jpg"],
    "美食": [
      "travel/海南/美食/IMG_1596.jpg",
      "travel/海南/美食/IMG_1608.jpg",
      "travel/海南/美食/IMG_1610.jpg",
      "travel/海南/美食/IMG_1611.jpg",
      "travel/海南/美食/IMG_1612.jpg",
      "travel/海南/美食/IMG_1638.jpg",
      "travel/海南/美食/IMG_1639.jpg",
      "travel/海南/美食/IMG_1640.jpg",
      "travel/海南/美食/IMG_1641.jpg",
      "travel/海南/美食/IMG_1642.jpg",
      "travel/海南/美食/IMG_1647.jpg",
      "travel/海南/美食/IMG_1648.jpg",
      "travel/海南/美食/IMG_1649.jpg",
      "travel/海南/美食/IMG_1650.jpg",
      "travel/海南/美食/IMG_1651.jpg",
      "travel/海南/美食/IMG_1652.jpg",
      "travel/海南/美食/IMG_1653.jpg",
      "travel/海南/美食/IMG_1654.jpg",
      "travel/海南/美食/IMG_1667.jpg",
      "travel/海南/美食/IMG_1669.jpg",
      "travel/海南/美食/IMG_1670.jpg",
      "travel/海南/美食/IMG_1675.jpg",
      "travel/海南/美食/IMG_1676.jpg",
      "travel/海南/美食/IMG_1677.jpg",
      "travel/海南/美食/IMG_1685.jpg",
      "travel/海南/美食/IMG_1686.jpg",
      "travel/海南/美食/IMG_1687.jpg",
      "travel/海南/美食/IMG_1689.jpg",
      "travel/海南/美食/IMG_1690.jpg",
      "travel/海南/美食/IMG_1691.jpg",
      "travel/海南/美食/IMG_1692.jpg",
      "travel/海南/美食/IMG_1693.jpg",
      "travel/海南/美食/IMG_1702.jpg",
      "travel/海南/美食/IMG_1703.jpg",
      "travel/海南/美食/IMG_1704.jpg",
      "travel/海南/美食/IMG_1709.jpg",
      "travel/海南/美食/IMG_1710.jpg",
      "travel/海南/美食/IMG_1712.jpg",
      "travel/海南/美食/dji_export_20260817_photo_0001.jpg",
      "travel/海南/美食/dji_export_20260821_photo_0001.jpg"
    ]
  },
  "重庆": [],
  "四川": [],
  "贵州": [],
  "云南": [],
  "西藏": [],
  "陕西": [],
  "甘肃": [],
  "青海": [],
  "宁夏": [],
  "新疆": [],
  "台湾": [],
  "香港": [],
  "澳门": []
};
